### ISSUE TITLE
🚧Update OpenAL

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#102]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the OpenAL libraries.

The current version being used is _**v1.21.1**_.  The version to update should be _**v1.23.0**_.
For the windows binaries, make sure to right click each file and confirm the versions.

In the project, there is a directory where you need to put the libraries for each platform.  The 3 platforms are **linux-64** and **win-x64**.

We are not supporting **win-x86** anymore.  This directory can be deleted.
There is also some setup in the **csproj** file to pack the **win-x86** version of the file into the NuGet package.  This can be removed.  Refer to diff below.

```diff
<Target Name="AddNativeWindowLibsToNugetPackage" AfterTargets="Build" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU' Or '$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <ItemGroup>
      <!--WINDOWS-->
-      <Content Include="$(ProjectDir)OpenAL\libs\win-x86\*.dll" Pack="true" PackagePath="\runtimes\win-x86\native" />
      <Content Include="$(ProjectDir)OpenAL\libs\win-x64\*.dll" Pack="true" PackagePath="\runtimes\win-x64\native" />
      
      <!--LINUX-->
      <Content Include="$(ProjectDir)OpenAL\libs\linux-x64\*.so*" Pack="true" PackagePath="\runtimes\linux-x64\native" />
    </ItemGroup>
  </Target>
```

### **Other Info:**
**Windows**
Get the Windows binaries [here](https://openal-soft.org/#download)

**Linux:**
Linux binaries are not available and must be built.
- [OpenAL Soft](https://github.com/kcat/openal-soft)
- [vcpkg](https://github.com/Microsoft/vcpkg)
> [!Note]
> This is a cross-plat C++ library manager and is used to help build Windows & Linux binaries

### Acceptance Criteria

- [x] OpenAL lib for **win-x86** deleted
- [x] **csproj** updated to stop packing the **win-x86** version of OpenAL into the NuGet package
- [x] **win-x64** version of library updated
- [x] **linux-64** version of library updated
- [x] NuGet package manually created and OpenAL files verified with correct version to verify that it is being packed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Issue put on hold until the research results have been completed with the issue below:
- #290 

The reason is because if OpenAL is replaced by RayLib, then there is no point in trying to update to the latest library

**Comment by CalvinWilkinson** [comment]
> Issue put on hold until the research results have been completed with the issue below:
> 
> * [🔬Look into replacing openal with raylib #290](https://github.com/KinsonDigital/CASL/issues/290)
> 
> The reason is because if OpenAL is replaced by RayLib, then there is no point in trying to update to the latest library

Issue taken off of hold status.

**Reason:**
The reason is that the research into the raylib replacement ended in a decision to keep using OpenAL to not lose maximum control over audio.
