### ISSUE TITLE
🚧Add badges to README

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#103]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Replace all of the badges from the old section with the badges in the new section.

**Old Badge Section:**
```markdown
<div align="center">

![](https://img.shields.io/github/workflow/status/KinsonDigital/CASL/%F0%9F%9A%80Preview%20Release?label=QA%20Release%20%F0%9F%9A%80&logo=GitHub&style=plastic)
![](https://img.shields.io/github/workflow/status/KinsonDigital/CASL/%F0%9F%9A%80Preview%20Release?label=Preview%20Release%20%F0%9F%9A%80&logo=GitHub&style=plastic)
![](https://img.shields.io/github/workflow/status/KinsonDigital/CASL/%F0%9F%9A%80Production%20Release?label=Production%20Release%20%F0%9F%9A%80&logo=GitHub&style=plastic)

![](https://img.shields.io/codecov/c/github/KinsonDigital/CASL/master?label=Code%20Coverage&logo=CodeCov&style=plastic)
[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.0-4baaaa.svg?style=plastic)](code_of_conduct.md)

![](https://img.shields.io/nuget/v/KinsonDigital.CASL?logo=nuget&style=plastic)

</div>
```

**New Badge Section:**
```markdown
<div align="center">

[![Production Release Status](https://img.shields.io/github/workflow/status/KinsonDigital/CASL/%F0%9F%9A%80Production%20Release?label=Production%20Release%20%F0%9F%9A%80&logo=GitHub&style=flat)](https://github.com/KinsonDigital/CASL/actions/workflows/qa-prod-releases.yml)
[![Preview Release Status](https://img.shields.io/github/workflow/status/kinsondigital/CASL/%F0%9F%9A%80Preview%20Release?color=%23238636&label=Preview%20Release%20%F0%9F%9A%80&logo=github)](https://github.com/KinsonDigital/CASL/actions/workflows/prev-release.yml)
[![Latest Nuget Release](https://img.shields.io/nuget/vpre/kinsondigital.CASL?label=Latest%20Release&logo=nuget)](https://www.nuget.org/packages/KinsonDigital.CASL)
![Nuget](https://img.shields.io/nuget/dt/KinsonDigital.CASL?color=0094FF&label=nuget%20downloads&logo=nuget)

</div>

<div align="center">

![Unit Test Status](https://img.shields.io/github/workflow/status/kinsondigital/CASL/%E2%9C%94Unit%20Testing%20Status%20Check?color=%23238636&label=Unit%20Tests)
[![Code Coverage](https://img.shields.io/codecov/c/github/KinsonDigital/CASL/master?label=Code%20Coverage&logo=CodeCov&style=flat)](https://app.codecov.io/gh/KinsonDigital/CASL)
[![Good First GitHub Issues](https://img.shields.io/github/issues/kinsondigital/CASL/good%20first%20issue?color=7057ff&label=Good%20First%20Issues)](https://github.com/KinsonDigital/CASL/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
</div>

<div align="center">

[![Discord](https://img.shields.io/discord/481597721199902720?color=%23575CCB&label=discord&logo=discord&logoColor=white)](https://discord.gg/qewu6fNgv7)
[![Twitter URL](https://img.shields.io/twitter/url?color=%235c5c5c&label=Follow%20%40KDCoder&logo=twitter&url=https%3A%2F%2Ftwitter.com%2FKDCoder)](https://twitter.com/KDCoder)
</div>
```

### Acceptance Criteria

- [x] Nuget downloads badge added to README

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by fab3** [comment]
Hi , I can replace those badges at least i can do :)
