### ISSUE TITLE
🚧Refactor unit test assertions

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#105]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor all of the unit test assertions to use the **FluentAssertions** library.
This will greatly cleanup the unit testing side of things and make the creation of unit tests easier.

> **Note**
> 1. We have been migrating all of our assertion code for the past 6 months from standard XUnit assertions API to [FluentAssertions API](https://fluentassertions.com/introduction) API.  Most of the code base has been converted and examples can be found all of the place.  Please don't hesitate to ask questions and for help if needed.
> 2. Please follow our [Contribution Guide](https://github.com/KinsonDigital/.github/blob/main/docs/CONTRIBUTING.md)
> 3. Join the [KinsonDigital Community](https://discord.gg/qewu6fNgv7)!!

### Acceptance Criteria

- [x] Latest version of FluentAssertions Nuget package added to the project
- [x] Refactor the files below: 
  - [x] `MP3SoundDecoderTests.cs` - 107 lines
  - [x] `OggSoundDecoderTests.cs` - 140 lines
  - [x] `SoundDataTests.cs` - 172 lines
  - [x] `AudioDeviceDoesNotExistExceptionTests.cs` - 60 lines

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if required)_.
- [x] Issue linked to the correct milestone _(if required)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by SyedMSawaid** [comment]
Assign me this as well.

**Comment by CalvinWilkinson** [comment]
@SyedMSawaid Just quick heads up on this one.  The unit tests related to sounds can be a little touchy because there is unsafe code in there.  There is a chance that some refactoring might have to be done with the mocking side of things, but not sure.  It has been awhile since I was in the code.

Usually, you do not have any logic inside of your unit tests and that is bad practice.  But at the time I had no choice and things needed to be tested I have plans to clean this up in the future.

**Comment by thestbar** [comment]
@CalvinWilkinson I would like to work on this one.
