### ISSUE TITLE
🚧Update contribution docs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#112]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the contribution docs to match that of the docs in the _**Velaptor**_ project.  This will be set up using issue KinsonDigital/Velaptor#408 as a guide.

Make sure the go through the document and change the required things for the context of this project.  Such as the places where the project name **_Velaptor_** is called out, needs to be changed to the project name _**CASL**_.

### Acceptance Criteria

- [ ] Contribution docs updated to match the set up as _**Velaptor**_ project.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes

**Reason:**
Change in direction with how contributions and access to those have been changed

**Comment by kselena** [comment]
Closed without changes

Reason: Change in direction with how contributions and access to those have been changed and it wasn't closed previously by mistake.
