### ISSUE TITLE
🚧Update build system to CICD

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#115]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the build system to use [CICD](https://github.com/KinsonDigital/CICD).

This will require removing all of the current workflows and using the workflows that come with CICD.
Update CICD to the latest version as of the implementation of this issue.

### Acceptance Criteria

- [ ] _**CICD**_ dotnet tool added to the solution
- [ ] Workflows replaced/updated.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Put on hold

**Reason:**
This is due to the unit tests failing.  This is occurring because pathing is currently only Windows-specific pathing, and the CICD system runs on **Ubuntu**.  This requires that the pathing code in the main project and in the unit tests all be converted to be cross-platform.

The issue below added as a dependency:
- #123

**Comment by CalvinWilkinson** [comment]
This issue set to a https://github.com/KinsonDigital/CASL/labels/%F0%9F%A7%A8breaking%20changes

**Reason:**
The `Sound` class was set to `sealed`.
