### ISSUE TITLE
🚧Process all warnings in code base

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#120]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Go through all of the warnings generated by the analyzers as well as the build results and process them.

This is a cleanup of the entire code base.

### Acceptance Criteria

- [x] Update all _**.editorconfig**_ files.
    > **Warning** Do this before processing any warnings
- [x] All analyzer warnings processed
- [x] All build warnings process
    > **Note** These are the warnings that you can see in the **Build** tab in **JetBrains Rider**
- [x] Go through all constructors and make all of the injected param code docs the same.
- [x] Add code docs to all unit test files with missing code docs

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
