### ISSUE TITLE
🚧Setup all pathing to be cross platform

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#123]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Go through the entire code base and make all of the patching cross-platform compatible.  

**Reason:**
1. This is going to be required for the future anyways due to the intent of being cross-platform
2. This is required for running unit tests on Ubuntu or any other OS environment.

To assist with this, create an extension method for converting paths to being cross-platform.

### Acceptance Criteria

- [x] Internal extension/helper method created for converting paths
    - [x] Unit tests created
- [x] Pathing code updated to be cross-platform

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
