### ISSUE TITLE
🚧Convert namespaces to file scoped

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#125]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Convert all of the namespaces in the code base from block-scoped to file-scoped namespaces.
This can easily be done with **Visual Studio** or **Rider** by using a build code transformation in the IDE.

As the conversions are made, please make sure that the `using` statements are all **BELOW** in the namespace declaration.  This will ensure that the `using` statements all following the current analyzer setup for the project.  CASL contains the `using` statements inside of the namespace, not outside.

> **Note**
> More info on this C# feature can be found [here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces) and [here](https://www.youtube.com/watch?v=HXm2sRtVT8Y)

**Before Transformation Example:**
```csharp
namespace CASL.Exceptions
{
    using System;
}
```

**After Transformation Example:**
```csharp
namespace CASL.Exceptions

using System;
```

### Acceptance Criteria

- [x] All namespaces converted to file-scoped

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
