### ISSUE TITLE
🚧Setup project Social Preview

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#133]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Do some research on setting up a project's **Social Preview** and set it up

**Refer to image below:**
![image](https://user-images.githubusercontent.com/85414302/167882641-750c4ce9-8ee1-410d-bbf0-d8afba31826e.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Social preview setup.

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kselena** [comment]
We need to create an image and set it in the GitHub settings.  No PR needed.
