### ISSUE TITLE
🚧Update maintainer Twitter link on home page

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#136]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

The link for @CalvinWilkinson's Twitter in the Maintainers section, currently points to another person.  Kristen's info is missing.

https://github.com/KinsonDigital/CASL 

<img width="558" alt="image" src="https://user-images.githubusercontent.com/96791049/216316097-dad8b112-d20a-46f7-8ca9-b1d6d299c89c.png">

### Acceptance Criteria

- [x] ReadMe updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
