### ISSUE TITLE
🚧Update Readme

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#160]
Complete The Item Below
 I have updated the title without removing the 🚧 emoji.
Description
We are in the process of rationalizing ReadMe across all GitHub Actions (GHA). This includes:

Making sure all sections are in this order:

1. Logo
2. Repo Name
3. Badges
4. Notice
5. About
6. Features
7. Add Demo (to be done at a later date by Calvin)
8. Contributing
9. Maintainers
10. License

**Contributing**
Use wording from Velaptor

Use Maintainers, Contributing and License section from Velaptor
Remove Practices section
Remove Further Resources section
Use emoji's like in Velaptor for each section
Double check spelling/grammar
Verify all links work and point correctly
Add Demo section like Velaptor
  >Note: CMW to do this

**Acceptance Criteria**
 
- [x] Sections are in this order:
- [x]  Logo
- [x]  Repo Name
- [x]  Badges
- [x]  Notice
- [x]  About
- [x]  Features
- [x]  Contributing is like Velaptor
- [x]  Maintainers is like Velaptor
- [x]  License is like Velaptor
- [x]  Emoji's are like Velaptor for each section
- [x]  Spelling/grammar checked
- [x]  All links work and point correctly

**ToDo Items**
- [x]  Change type labels added to this issue. Refer to the Change Type Labels section below.
- [x]  Priority label added to this issue. Refer to the Priority Type Labels section below.
- [x]  Issue linked to the correct project (if applicable).
- [x]  Issue linked to the correct milestone (if applicable).
- [x]  Draft pull request created and linked to this issue (only required with code changes).

**Issue Dependencies**
No response

**Related Work**
No response

**Code of Conduct**

- [x]  I agree to follow this project's Code of Conduct.
