### ISSUE TITLE
🚧Update deprecated step output

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#166]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Please update the various steps in various workflows to use the new output setup instead of the deprecated one.
The current way of setting steps still uses the method that will be deprecated by GitHub in May.

**Workflows Are:**
1. hotfix-pr-status-check.yml
2. build-pr-status-check.yml
3. feature-pr-status-check.yml
4. prev-feature-pr-status-check.yml
5. prod-release-pr-status-check.yml
6. prev-release-pr-status-check.yml
7. unit-test-pr-status-check.yml

**Upgrade Example:**
```diff
- Write-Host "::set-output name=pr-number::$pullRequestNumber";
+ "pr-number=$pullRequestNumber" >> $GITHUB_OUTPUT;
```

### Acceptance Criteria

```[tasklist]
- [x] build-pr-status-check.yml updated
- [x] unit-test-pr-status-check.yml updated
- [x] feature-pr-status-check.yml updated
- [x] prev-feature-pr-status-check.yml updated
- [x] prev-release-pr-status-check.yml updated
- [x] prod-release-pr-status-check.yml updated
- [x] hotfix-pr-status-check.yml updated
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
