### ISSUE TITLE
🚧Add rule to solution editorconfig

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#168]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a new rule to the solution-wide **.editorconfig** file to ignore warnings and suggestions for outside `using` statement placement.

**Here is the rule to add:**
```ini
# IDE0065: Misplaced using directive
csharp_using_directive_placement = inside_namespace
```

> **Note** There are two **_.editorconfig_** files in this solution.  One is in the root of the repo and it is the _**root**_ config file.  The other is in the _**Testing/**_ directory and are additional rules for the unit tests projects.  The unit testing config file inherits the rules from the solution level config file.

> **Note** This will remove any warnings in **_Visual Studio_** about moving the using statements outside of the namespaces.  _**JetBrains Rider**_ users should not get this warning.

### Acceptance Criteria

> **Note** The tasks below need to be done in the order below.

```[tasklist]
### Tasks
- [x] The solution level config updated
- [x] The testing level config updated
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
