### ISSUE TITLE
🚧Add full file path to CASL logo

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#186]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In the ReadMe, the logo currently points to: https://github.com/KinsonDigital/CASL/blob/release/v1.0.0/README.md.  However, in order to use the logo in other parts of the documentation, the full, raw file path needs to be in place. 

Use this as a guide: "https://raw.githubusercontent.com/KinsonDigital/Velaptor/release/v1.0.0/Documentation/Images/velaptor-logo.png

### Acceptance Criteria

- [x] CASL logo uses full, raw file path

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by kselena** [comment]
While  working on the issue, it was discovered that this issue has already been done with the following issue:
- #39.
