### ISSUE TITLE
🚧Create auto project workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#196]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a workflow that automatically adds issues and prs to the **KD-Team** project.
This will use deno to execute a script in the **Infrastructure** repository.  The script to execute will be the _**./cicd/scripts/add-item-to-project.ts**_ typescript file.

### **Issue workflow needs to:**
1. File name should be 👉🏻 **add-issue-to-project.yml**
2. Run with the `issues>opened` event
3. Setup deno
4. Execute the deno script mentioned above.
> **Note** Use the latest version tag in the **Infrastructure** script as part of the script path.  Should be the latest version.

### **PR workflow needs to:**
1. File name should be 👉🏻 **add-pr-to-project.yml**
2. Run with the `pull_request>opened` event
3. Setup deno
4. Execute the deno script mentioned above.
> **Note** Use the latest version tag in the **Infrastructure** script as part of the script path.  Should be latest version.

> **Note** The script takes various arguments.  These arguments will be sent to the script in the `deno run` command that you will add to the workflow.  Additional info is in the script itself.  Use it as a reference.
The script takes the following arguments:
> 1. Repo Name
> 2. Issue Or PR Number
> 3. Item Type
> 4. Project Name
> 5. GitHub Token

### Acceptance Criteria

- [x] Workflow created for auto-adding issues to the KD-Team project
- [x] Workflow created for auto-adding prs to the KD-Team project
- [x] Change default branch back to master 
- [x] Add the 🤖 to the beginning of both workflow names

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
