### ISSUE TITLE
🚧Create preview release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#215]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a preview release workflow.  This workflow will perform validation of various things before performing the release.
A release will consist of the combination of creating a NuGet package, publishing the package, creating a GitHub release with attached release notes, and announcing the release on Twitter.

Pay attention to the following:
1. Make sure the entire workflow uses **powershell** as the default shell
2. The version will be validated that it is a **preview** version
4. The branch to validate will be validating that the head branch is a **preview** branch
    - This uses the **BranchValidator** GitHub action
5. The jobs need to have dependencies on other jobs to ensure certain operations are performed before that job is executed.
> **Note** These dependencies can be seen in the graph below.

The diagram below shows the dependencies between the jobs in the workflow.
![prev-workflow-dep-graph](https://github.com/KinsonDigital/CASL/assets/85414302/36594f93-47d1-431f-bccf-987550550269)

### Acceptance Criteria

- [x] Preview Release Workflow Created
    - [x] Workflow named _**preview-release.yml**_
    - [x] Job created to validate that the head branch is a **preview** branch
    - [x] Job created to pull the version from the _**.csproj**_ file
        > **Note** Uses the **VersionMiner** action
    - [x] Job created to validate that the version is a **preview** version
        > **Note** Uses the _**validate-version.ts**_ script
    - [x] Job created to validate that the tag is correct
        > **Note** Uses the _**validate-tag.ts**_ script
    - [x] Job created to validate that the NuGet package exists
        > **Note** Uses the _**nuget-pkg-does-not-exist.ts**_ script
    - [x] Job created to validate that the release notes exist and that the contents of the release notes
        > **Note** Uses 2 steps in a single job. Need to validate the existence of the release notes
        > first before we check the note's content
        > - Uses the _**release-notes-exist.ts**_ script
        > - Uses the _**validate-release-notes.ts**_ script
    - [x] Job created to validate that the milestone exists and that the items are all closed
        > **Note** Uses 2 steps in a single job. Need to validate the existence of the milestone exists
        > first before we check if the milestone items are all closed
        > - Uses the _**milestone-exists.ts**_ script
        > - Uses the _**milestone-items-all-closed.ts**_ script
    - [x] Job created to validate that a GitHub release does not already exist'
        > **Note** Uses the _**github-release-does-not-exist.ts**_
    - [x] Job created to build all projects
    - [x] Job created to run all tests
    - [x] Job created to perform the actual release
        > **Note** This will contain many steps for the release process.
        > - Create a NuGet package
        > - Publish NuGet Package
        > - Create GitHub release (Uses the [soft props](https://github.com/marketplace/actions/gh-release) GitHub action
        > - Perform Twitter announcement
        > - Close Milestone
- [x]  Change default branch back to master

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- KinsonDigital/Infrastructure#27
- KinsonDigital/Infrastructure#32

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
