### ISSUE TITLE
🚧Setup project for issue syncing

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#223]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Set up the project for issue syncing by creating workflows to utilize the org-level CICD scripts for syncing pull requests with the issues.

### **Create the following:**
1. Create a workflow named _**sync-bot-status-check.yml**_ which will be used as a sync bot when issues change and also as a status check for pull requests if the pull request is not in sync with the issue.
2. Create a workflow named _**sync-issue-to-pr.yml**_ which will be used to manually sync pull requests with an issue upon creation as well as manually via a custom command via pull request comments.

The version to point to will be the latest which as of the creation of this issue is _**v6.0.0**_.  Pointing to the new version will be done via a repository variable named **CICD_SCRIPTS_VERSION**.

Also, remove the _**add-issue-to-project.yml**_ and _**add-pr-to-project.yml**_ workflows from the project.  These will be useless now that the syncing process takes care of this.

### Acceptance Criteria

- [x] _**add-issue-to-project.yml**_ workflow removed
- [x] _**add-pr-to-project.yml**_ workflow removed
- [x] _**sync-bot-status-check.yml**_ workflow created
- [x] _**sync-issue-to-pr.yml**_ workflow created

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
