### ISSUE TITLE
🚧Fix badges in readme

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#228]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the badges in the readme.

Remove the production version but do not remove it.  This is because the project has not made it into production yet.

Fix the preview badge by having it point to the build status check workflow.
Add a new badge that points to the unit testing status check workflow.

### Acceptance Criteria

- [x] Production badge removed
- [x] build badge converted to build status check badge
- [x] unit testing status check badge added

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [X] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
