### ISSUE TITLE
🚧Fix broken image link in readme

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#237]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the broken image link, Codecov and License in the readme file.  This is due to the changing of the branching model.  Before the image URL was pointing to the _**preview/v1.0.0**_ branch but this branch does not exist anymore.

The default branch is now **preview** until we move to _**v1.0.0**_ which at that point, it will become _**main**_.

Update the URL's to point to the _**preview**_ branch.

### Acceptance Criteria

- [x] Broken logo image in the readme file fixed
- [x] Broken Codecov image in the readme file fixed
- [x] Broken License image in the readme file fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
