### ISSUE TITLE
🚧Fix release workflow input

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#276]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

For the _**release.yml**_ workflow, there is a reusable workflow input that is being sent to the incorrect repository variable.

The variable being used is `RELATIVE_RELEASE_NOTES_DIR_PATH`.  This is an old variable that does not exist anymore and has been replaced with `PREV_RELATIVE_RELEASE_NOTES_DIR_PATH` and `PROD_RELATIVE_RELEASE_NOTES_DIR_PATH` variables.

Fix this by doing the following:
1. Create a job that the `run_release` job depends on, that chooses the correct dir path based on the type of release being performed.
2. Use the new job output as the input to the  `relative-release-notes-dir-path` workflow input.

### Acceptance Criteria

- [x] Release workflow updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
