### ISSUE TITLE
🚧Fix issue in prepare release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#278]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue in the _**prepare-release.yml**_ workflow where the job `print_validate_workflow` has logic in the powershell script that checks the type of release.

Fix shown below:
```diff
- if ($releaseType -ne 'preview' -and $releaseType -ne 'roduction') {
+ if ($releaseType -ne 'preview' -and $releaseType -ne 'production') {
  Write-Host "::error::The release type input must be either 'Preview' or 'Production'.";
  exit 1;
}
```

### Acceptance Criteria

- [x] powershell code fixed in workflow job

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
