### ISSUE TITLE
🔬Look into replacing openal with raylib

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#290]
### Complete The Item Below

- [X] I have updated the title without removing the 🔬 emoji.

### What To Research

Look into possibly replacing OpenAL with raylib.

```[tasklist]
### Things to research:
- [x] Audio can be paused and played from the pause point
- [x] Audio can be re-winded
- [x] Audio can be fast-forwarded
- [x] Audio can be played at different speeds
- [x] Is raylib sound hardware or software rendering or both?
- [ ] What kinds of code changes will there be to use raylib instead of OpenAL
- [x] Impact of using multiple sounds
- [x] Research streaming of sound
- [ ] Look into how the public API might change to get raylib working under the hood.
- [x] Research licensing
- [x] Sound can be looped (YES)
```

> [!Note]
> There is a type in raylib that lets you play a sound but only 1 at a time.  There is also another type that ends with `multi` used for playing multiple sounds at once. This will be important for games.

Create a prototype for these various things to test

### Research Results

> [!Warning]
> There is an issue currently where raylib crashes when an audio device changes.
> What this means is if you have headphones and you turn the headphones off, the operating system will change
> to the next default audio device, but raylib will not and it will crash.
> There is an open issue in the repository for this.
> - raysan5/raylib#3743

---

<details><summary>Software vs Hardware Rendering</summary>
<p>

It is unknown for sure but from the research, it seems that it does not matter in the end.
Raylib uses the C library [miniaudio](https://miniaud.io/).

**This is what I found during my research:**
[Miniaudio is a low-level library that provides an interface to the underlying audio devices on your system](https://miniaud.io/docs/manual/index.html)[1](https://miniaud.io/docs/manual/index.html). [It supports playback, capture, full-duplex, and loopback](https://miniaud.io/docs/manual/index.html)[1](https://miniaud.io/docs/manual/index.html).

[The library gives you access to the raw audio data of an audio device](https://miniaud.io/docs/manual/index.html)[1](https://miniaud.io/docs/manual/index.html). [It allows you to choose a physical device to emit or capture audio from, and then move data to/from the device when miniaudio tells you to](https://miniaud.io/docs/manual/index.html)[1](https://miniaud.io/docs/manual/index.html). [Data is delivered to and from devices asynchronously via a callback which you specify when initializing the device](https://miniaud.io/docs/manual/index.html)[1](https://miniaud.io/docs/manual/index.html).

However, the actual rendering of the audio - whether it’s done in software or hardware - is typically handled by the underlying audio system of the operating system, not by the miniaudio library itself. The library’s role is more about providing a convenient and portable way to interact with that system.

So, in summary, miniaudio itself doesn’t directly handle software or hardware audio rendering. It provides a way to send and receive audio data to/from the audio devices, and the actual rendering is handled by the underlying system. This approach allows miniaudio to be lightweight and portable across different platforms and audio systems.

</p>
</details> 

---

<details><summary>Audio Play/Pause/Restart</summary>
<p>

Audio can be played, paused, and restarted.
Go [here](https://www.raylib.com/examples/audio/loader.html?name=audio_music_stream) for a sample of how it is done.

</p>
</details> 

---

<details><summary>Multiple sounds</summary>
<p>

Raylib does support the use of multiple sounds playing at the same time.
An example of this can be found [here](Impact of using multiple sounds)

</p>
</details> 

---

<details><summary>Licensing</summary>
<p>

All raylib components use the _**ZLib License**_.  There won't be any issues/conflicts with using this software in terms of licensing.

**zlib License**
	
Copyright (c) 2014-2024 Ramon Santamaria (@raysan5)

This software is provided "as-is", without any express or implied warranty. In no event 
will the authors be held liable for any damages arising from the use of this software.

Permission is granted to anyone to use this software for any purpose, including commercial 
applications, and to alter it and redistribute it freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not claim that you 
  wrote the original software. If you use this software in a product, an acknowledgment 
  in the product documentation would be appreciated but is not required.

  2. Altered source versions must be plainly marked as such, and must not be misrepresented
  as being the original software.

  3. This notice may not be removed or altered from any source distribution.

</p>
</details> 

### Acceptance Criteria

**This issue is finished when:**
- [ ] Research complete and issues created _(if needed)_.
- [ ] If any issues were created, they have been added to the _**Related Work**_ section below.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
It was decided after doing this research to not use raylib.  The reason is due to the lack of some of the control as well as how it works.  It _**CAN**_ be done successfully, but the need to have maximum control has drove the decision to keep using OpenAL to get these benefits.
