### ISSUE TITLE
🚧Update xunit dependency

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#294]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the **_xunit_** dependency NuGet package to version _**2.5.1**_.

### What is this?
This package is used for performing unit testing across the project.  The update to be performed is a patch update which means that it is very very low risk to update to this new version.

Currently, the version is at _**2.5.0**_.

### What do I need to do?

All you need to do is go into the _**CASLTests.csproj**_ file and manually update the version to version _**2.5.1**_.

Here is what you are looking for in the file:

First package/dependency to update
```diff
-    <PackageReference Include="xunit" Version="2.5.0" />
+     <PackageReference Include="xunit" Version="2.5.1" />
```

Second package/dependency to update
```diff
-    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0">
+    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.1">
```

### Where do I find the file?
The file can be found in the following folder:
_**./CASL/CASLTesting/CASLTests**_

> **Note**
> The directory path above is relative to the root of the repository on your machine.

### Acceptance Criteria

- [ ] The _**xunit**_ NuGet package is updated from version _**2.5.0**_ to _**2.5.1**_
- [ ] The _**xunit.runner.visualstudio**_ NuGet package is updated from version _**2.5.0**_ to _**2.5.1**_

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by Zareck521** [comment]
I would like to pick up the issue.

**Comment by KinsonDigitalAdmin** [comment]
Closed without implementation.  Refer to PR for more info.
