### ISSUE TITLE
🚧Convert all OpenAL interop to use silk dotnet

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#337]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Convert all code that uses custom interop PInvokes and the loading of the OpenAL library to use Silk dotnet instead.

**Why?**
The reason for this is 2 fold.   It will reduce the amount of interop code that will need to be maintained and it will also take advantage of the hard work that the people have put behind the silk dotnet APIs.  They are better at making sure performance is taken into consideration as well as cross-platform concerns.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [ ] All OpenAL interop code replaced by silk dotnet code
- [ ] Create an OpenALService class to provide a simpler internal API
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without completion.  During the implementation, it was discovered that getting a list of devices as well as managing when a device is disconnected or not connected was not as straightforward. It seems like the use of the interop into the **_OpenAL_** [alcGetString](https://www.openal.org/documentation/OpenAL_Programmers_Guide.pdf#page=117&zoom=100,0,0) function in **_silk dotnet_** does not give you the ability to get a list of all the devices like the current implementation in _**CASL**_.

Getting devices, device management, and choosing different devices is a feature that exists in **_CASL_** and we do not want to give that up.  Maybe in the future, this is something that silk will provide and we can take advantage of this then.
