### ISSUE TITLE
🚧 Project Item - Create version status check workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#37]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### ---
Description

Create a new status check workflow for production releases that uses a _**actions/github-script@v4**_ action to check the version and make sure that it **DOES NOT** have the **-preview.** syntax. If it does, then of course the status check will fail.

### Acceptance Criteria

**This issue is finished when:**
1. [x] Status check runs successfully

### ToDo Items

- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- #7
- #34
