### ISSUE TITLE
🚧Add README to NuGet package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#39]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a README.md to the NuGet package. 
This can be done by making some changes to the _**.csproj**_ file.

### **Resources:**
- [Add README to your package blog](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/)
- [Package ReadMe File (MsDocs)](https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile)
- [Package readme on NuGet.org](https://learn.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org)

Refer to the issue in the dependencies section below for more info.

**Here are the things to add:**
```xml
<PackageReadmeFile>README.md</PackageReadmeFile>
```

```xml
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
```

**Project File:**
```diff
    <PackageIconUrl />
    <PackageId>KinsonDigital.CASL</PackageId>
    <PackageIcon>casl-logo.png</PackageIcon>
+  <PackageReadmeFile>README.md</PackageReadmeFile>
```

```diff
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
+   <None Include="..\README.md" Pack="true" PackagePath="\"/>
```

### Acceptance Criteria

**This issue is finished when:**
- [x] **README** added to package.

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- KinsonDigital/CICD#121

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

**Comment by CalvinWilkinson** [comment]
Issue put on hold.  This was due to the feature not being finished yet.
This feature is currently in preview and we have to wait until its ready for production.

More info can be found [here](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/)
