### ISSUE TITLE
🚧 Project Item - Add status check workflow for tag verification

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#41]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

---

### Description

Add the new [TagVerifier@v0.1](https://github.com/KinsonDigital/TagVerifier) action verify that the tag does not already exist.

### Acceptance Criteria

**This issue is finished when:**
1. [x] New check status workflow file created
2. [x] Status check setup for _**release/v\*\.\*.\***_ branches
3. [x] New status check workflow named _**tag-exists-status-check.yml**_
4. [x] Workflow status check runs successfully.

### ToDo Items

- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
