### ISSUE TITLE
🚧 Project Item - Create status check for prod release versions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#42]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create status check to be able to verify production release numbers for proper syntax.

### Acceptance Criteria

**This issue is finished when:**
- [x] Production version status check script created
    * Name the script file **_prod-version-status-check.js_**
    * Put the script file in the _**status-check-scripts**_ directory
- [x] Production version status check workflow created
    * This uses the **_prod-version-status-check.js_** script

### ToDo Items

- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
