### ISSUE TITLE
🚧 Project Item - Create status check workflow for project builds & tests

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#51]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a workflow to be ran as a status check for pull requests that runs a build and/or unit tests for PR's to be accepted.

Look into how the status check logging works in the PR to decide if the _**build**_ and **_unit test_** status checking should be done.  It might be better to have 2 separate status workflows.  One for building and one for running unit tests.

### Acceptance Criteria

**This issue is finished when:**
- [x] Build Status Check Workflow runs
- [x] Unit Tests Status Check Workflow runs
- [x] Status check info in the PR is understandable

### ToDo Items

- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
