### ISSUE TITLE
🚧Create status check for preview labeling

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#52]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a status check workflow that checks to make sure that the PR is labeled with the _**preview**_ label.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Workflow runs
- [ ] Workflow only runs for _**release/**_ branches which are for preview
- [ ] The workflow can be ran manually by using _**workflow_dispatch**_

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)

**Comment by teezzan** [comment]
I would love to handle this. I would appreciate a pointer though. Thanks.

**Comment by CalvinWilkinson** [comment]
Sure thing.

If you look at the [Velaptor workflows](https://github.com/KinsonDigital/Velaptor/tree/preview/v1.0.0-preview.3/.github/workflows), you can use these as a guide/reference to help you out on workflow related stuff.

To make sure that it is only for a release branch, you just have to setup the workflow to run for pull request events only and against a release branch using this below.
``` yml
on:
  workflow_dispatch:
  pull_request:
    types: [ synchronize ]
    branches: [
      release/v*.*.*
    ]
```

The _**workflow_dispatch**_ in the YAML sets the workflow up to be able to ran manually. I like having this on my workflows to be able to execute them manually for troubleshooting purposes or for simple verification.

As for checking if a pull request does or does not have certain labels, you [this github action](https://github.com/marketplace/actions/verify-pull-request-labels)
