### ISSUE TITLE
🚧Update all workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#53]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update all of the workflows to match the current workflow setup in the **Velaptor** project.

### Acceptance Criteria

**This issue is finished when:**
The following workflows added/changed:
- [x] build-status-check.yml
    - [x] Runs
    - [x] workflow_dispatch event added
- [x] feature-pr-branches-status-check.yml
    - [x] Runs
    - [x] workflow_dispatch event added
- [x] tag-does-not-exist-status-check.yml
    - [x] Runs
    - [x] workflow_dispatch event added
- [x] unit-testing-status-check.yml
    - [x] Runs
    - [x] workflow_dispatch event added
- [x] validate-preview-release-branches-status-check.yml
    - [x] Runs
    - [x] workflow_dispatch event added
- [x] validate-prod-release-branches-status-check.yml
    - [x] Runs
    - [x] workflow_dispatch event added
- [x] version-status-check.yml
    - [x] Runs
    - [x] workflow_dispatch event added
- [x] preview-release.yml
    - [x] Runs
    - [x] broadcast to social media job fixed
        - Refer to related work section for more info
- [x] qa-prod-release.yml
    - [x] Runs
    - [x] broadcast to social media job fixed
        - Refer to related work section for more info

Make sure to fix the issue with the **Broadcast_To_Social_Media** job:

- [x] broadcast to social media job fixed for **prev-release.yml** workflow

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)

### Related Work

- Broadcast to social media job issue KinsonDigital/Velaptor#58
