### ISSUE TITLE
🚧 Project Item - Update gh-release action version

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#55]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the github action _**softprops/action-gh-release**_ from **v0.1.8** to **v0.1.10**

### Acceptance Criteria

**This issue is finished when:**
- [x] All workflows work correctly

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
