### ISSUE TITLE
🚧 Project Item - Add nuget version checker action to workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#59]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add the new [KinsonDigital/NugetVersionChecker](https://github.com/KinsonDigital/NugetVersionChecker) action to the preview and production release workflows.

This action will verify if the nuget package of a particular version already exists.  This is mostly to make sure that accidental releases are not performed with a version that already exists in nuget.org.

### Acceptance Criteria

**This issue is finished when:**
- [x] **_Validate Version Syntax_** job renamed to **_Validate Version_**
![image](https://user-images.githubusercontent.com/85414302/129241512-147c3979-1686-439a-9dd5-fc5cc8d57f71.png)
- [x] Preview release workflow updated to use new action
- [x] Production release workflow updated to use new action

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
