### ISSUE TITLE
🚧 Update all issue templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#62]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update all of the issue templates to match the **Velaptor** project.

### Acceptance Criteria

**This issue is finished when:**
The following issue templates updated:
- [x] bug-issue-template.yml
- [x] feature-request-issue-template.yml
- [x] project-item-issue-template.yml
- [x] Make sure to fix grammar issue in the **bug issue template**
    - [x] This should be labeled
        - **If you now what OS version the bug occurred on, enter the OS version here**

**Incorrect Grammar Screenshot:**
![image](https://user-images.githubusercontent.com/85414302/133952843-129c4f3a-8cb2-46f8-a60a-487ffe595ea9.png)

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
