### ISSUE TITLE
🚧Update all PR templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#63]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update all of the PR templates to match the templates in the **Velaptor** project.

### Acceptance Criteria

**This issue is finished when:**
- [x] ~PR template updated~

Following templates updated:
- [x] feature-to-develop.yml
- [x] preview-release-to-release.yml
- [x] release-to-master.yml

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] ~~Unit tests have been written and/or adjusted for code additions or changes~~
- [x] ~~All unit tests pass~~
