### ISSUE TITLE
🚧Update branching model diagram

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#64]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the branching model diagram to reflect preview releases.

This much represent that every preview release also can be merged into the develop branch to keep them up to date.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Diagram updated

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by CalvinWilkinson** [comment]
Non release notes not added.  This is because there are no release notes before any preview or production release notes.
