### ISSUE TITLE
🚧 Project Item - Replace version check scripts with VersionValidator GitHub action

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#65]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Replace the version validation scripts with the use of the new **VersionValidator** github action.  The new github action now performs the proper validation of the version as well as pulling the version out of the **.csproj** file for use by the rest of the pipeline.

### Acceptance Criteria

**This issue is finished when:**
- [ ] **workflows/status-check-scripts** folder and all of its contents removed
- [ ] Workflow files that use these scripts updated to use the new **VersionValidator** action

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~

**Comment by CalvinWilkinson** [comment]
Closed.  #53 will be taking care of this
