### ISSUE TITLE
🚧Improve sound loading performance

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#66]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Use the Rider line by line profiling tool to find the hot path when loading sounds and find a way to improve performance.

### Acceptance Criteria

**This issue is finished when:**
- [x] Performance investigation performed
- [x] If something can be improved, refactor code to improve performance

### ToDo Items

- [x] ~Draft pull request created and linked to this issue~
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] ~Unit tests have been written and/or adjusted for code additions or changes~
- [x] ~All unit tests pass~

**Comment by CalvinWilkinson** [comment]
After further investigation, the performance bottle neck is not in this code base but within the NVorbis library itself.  At this point there is no way to improve performance unless we switch to another library or build a custom implementation library to decode OGG Vorbis files using the C libraries.

Refer to [Xiph](https://xiph.org/) website for more information
