### ISSUE TITLE
🚧 Add kofi as a way to sponsor the project

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#67]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add a **_FUNDING.yml_** file to the _**.github**_ folder with a kofi sponsorship button setup.

Add the single line `ko_fi: kinsondigital` to the file

### Acceptance Criteria

**This issue is finished when:**
- [ ] Ko-fi setup as a funding option

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass
