### ISSUE TITLE
🚧 Add twitter badge to the README file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#68]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add a twitter badge to the _**README.md**_ file

This is the badge to use:
``` md
![Twitter URL](https://img.shields.io/twitter/url?label=Follow%20@KDCoder&logo=twitter&style=plastic&url=https%3A%2F%2Ftwitter.com%2FKDCoder)
```

### Acceptance Criteria

**This issue is finished when:**
- [x] Twitter badge added right below the nuget badge in the markdown file which will show the twitter badge to the right of the nuget badge

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] ~Unit tests have been written and/or adjusted for code additions or changes~
- [x] ~All unit tests pass~
