### ISSUE TITLE
🚧Update png and ico logo icon file types with new logo

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#75]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the _**png**_ and _**ico**_ file type version of the logo with the new logo that is currently used in the main **_README.md_** file.

There is a chance that the new logo with the brick design will not look good once it is shrunk to icon size. If this is the case, look into creating a better design just for the icons or simply just continue to use the old icon.

### Acceptance Criteria

**This issue is finished when:**
- [ ] PNG icon logo updated
- [ ] ICO icon logo updated

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Closed 

Reason:  Both icons have already been created and are being used.
