### ISSUE TITLE
🚧Update NuGet pkg info

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#76]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

1. Update the author to the NuGet package to show **Kinson Digital Team**.
2. Update the license URL to point to the license of the file in the repo on GitHub

**Example:**
![image](https://user-images.githubusercontent.com/85414302/187389598-8a989474-85ef-47f6-981d-28f5e4ce9a67.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Author updated in package
- [x] License URL updated in package

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
