### ISSUE TITLE
🚧Setup dependency labels

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#79]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Setup dependency labels to match what the **Velaptor** project has.

Go through all of the labels and verify they match.

### Acceptance Criteria

**This issue is finished when:**
- [x] All labels match that of **Velaptor**

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
