### ISSUE TITLE
🚧Update existing issue templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#80]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the following issue templates so they match the **Velaptor** project:
- `bug-issue-template.yml`
- `feature-request-issue-template`
- `project-item-issue-template`

### Acceptance Criteria

**This issue is finished when:**
- [ ] `bug-issue-template.yml`
- [ ] `feature-request-issue-template`
- [ ] `project-item-issue-template`

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] All unit tests pass

### Issue Dependencies

- KinsonDigital/Velaptor#284

**Comment by kselena** [comment]
@KinsonDigitalAdmin this has been completed, correct?

**Comment by CalvinWilkinson** [comment]
Closed for reason: duplicate of the issue below:
- #89
