### ISSUE TITLE
🚧Setup PR templates to match the Velaptor project

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#82]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

This issue is to get the PR templates of this project to match what is setup in the template repository project.
This needs to wait until the a template repository is created regarding the **Administration Cleanup** project.

### Acceptance Criteria

**This issue is finished when:**
- [ ] PR Templates updated

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [ ] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [ ] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Issue Dependencies

- KinsonDigital/issues-repo#9

**Comment by kselena** [comment]
Closed. 

Work done on issue below:
-#89
