### ISSUE TITLE
🚧Update branching docs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#83]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

The branching documentation is out of date.  Update the branching documentation to match that of the **Velaptor** project.

All you have to do is copy and paste in the content of the `Branching.md` file into the same file in this project.  Make sure that you search for project names and replace them with **CASL**

### Acceptance Criteria

**This issue is finished when:**
- [x] Code documentation added if required
- [x] All project name references updated and correct
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Issue Dependencies

- KinsonDigital/Velaptor#147
