### ISSUE TITLE
🚧Add new issue templates to project

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#84]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add the the following issue templates to the project.
NOTE: These are from the [Velaptor](https://github.com/KinsonDigital/Velaptor) project

**Templates To Add:**
- `qa-testing-template.yml`
- `release-todo-issue-template.yml`
- `research-issue-template.yml`

Also add a `config.yml` file with the following content:
```yml
blank_issues_enabled: false
```

### Acceptance Criteria

**This issue is finished when:**
- [ ] `qa-testing-template.yml`
- [ ] `release-todo-issue-template.yml`
- [ ] `research-issue-template.yml`
- [ ] Update preview feature PR template to match Velaptor
- [ ] `config.yml` file added

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Issue Dependencies

- KinsonDigital/Velaptor#296
- KinsonDigital/Velaptor#295
- KinsonDigital/Velaptor#298

**Comment by CalvinWilkinson** [comment]
Closed
**Reason:**  This was implemented by the issue below:
- #89
