### ISSUE TITLE
🚧Update Readme file

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#85]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update Readme file (remove the word actually) to the value below:

```diff
- 4. Once you've pushed a commit, open a [**draft pull request**](https://github.blog/2019-02-14-introducing-draft-pull-requests/). Do this **before** you actually start working.
+ 4. Once you've pushed a commit, open a [**draft pull request**](https://github.blog/2019-02-14-introducing-draft-pull-requests/). Do this **before** you start working.
```

### Acceptance Criteria

**This issue is finished when:**
- [x] Readme file is updated

### ToDo Items

- [X] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

**Comment by KinsonDigitalAdmin** [comment]
@Kshitiz-Mhto FYI - This work was done by @kselena and she did not notice that you had a PR already created for it.  I will be accepting your PR, not hers.

**Comment by KinsonDigitalAdmin** [comment]
@kselena I noticed that you unassigned this few days ago.  Probably had to do with the @Kshitiz-Mhto picking it up.
I simply reassigned it during my code review.

**Comment by KinsonDigitalAdmin** [comment]
Closed without changes.

Refer to PR comments on reason.
