### ISSUE TITLE
🚧Update Code of Conduct

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#86]
### I have done the items below . . .

- [x] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update code of conduct file.  Use the file below:
[code_of_conduct.md](https://github.com/KinsonDigital/CASL/files/9258108/code_of_conduct.md)

### Acceptance Criteria

**This issue is finished when:**
- [x] Code of Conduct file updated

### ToDo Items

- [X] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass
