### ISSUE TITLE
🚧Fix broken enhancement label link

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#87]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

The label was changed but the link is still pointing to the old enhancement label.  
The old enhancement label was changed and this is how the link has become broken.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Label link is updated

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by CalvinWilkinson** [comment]
Will be implemented in issue below:
- #312
