### ISSUE TITLE
🚧Add release note templates

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#88]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add preview and production release note template files.

### Acceptance Criteria

**This issue is finished when:**
- [x] Both preview and production templates are added

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass
