### ISSUE TITLE
🚧Add/Update issue and PR templates

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/CASL#89]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update issue and PR templates to match the templates from Velaptor

### Acceptance Criteria

**This issue is finished when:**
- Issue templates updated
  - [x] bug-issue-template.yml updated
  - [x] feature-request-issue-template.yml updated
  - [x] release-todo-issue-template.yml updated
  - [x] project-item-issue-template.yml updated
  - [x] qa-testing-template.yml updated
  - [x] research-issue-template.yml updated
- PR templates updated and text `-template` added to the end of the file before the file extension
  - [x] feature-pr.md
  - [x] preview-feature-pr.md
  - [x] preview-release-pr.md
  - [x] production-release-pr.md
- [x] Add/update config.yml
- [x] Add/update URL's

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass
